### ISSUE TITLE
Shutdown VMs serially leads to slow upgrade process

### ISSUE THREAD

**Issue by mordechai** [oVirt/ovirt-ansible-cluster-upgrade#21]
**Problem**: Currently in large environments where many vms  require being set down/up this happens in a serial fashion.  This makes upgrade process take a very long for large environments with many VMs.  

**Requested**: Add concurrency to starting/stopping VMs,
For example: Separate out vm start stop process to external yml task file and use batch command set at 20.

eg: https://github.com/oVirt/ovirt-ansible-cluster-upgrade/blob/64cf4059d8941399192a6453ca9172f7c982957b/tasks/main.yml#L69
might look like:

```
        - include: vms.yml
          loop_control:
            loop_var: vm_iter
          with_items:
                - "{{ stopped_vms | batch(20) | list  }}"
          when: stopped_vms | default([]) | length > 0
          var:
            vm_status: 'stopped'
```
vms.yml might look like:

```
- name: Async sleeping for batched_items
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: "{{vm_staus}}"
    force: true
    name: "{{ async_item.name }}"
  async: 4000
  poll: 0
  with_items: "{{ vm_iter }}"
  loop_control:
    loop_var: "async_item"
  register: async_results

- name: Check sync status
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  with_items: "{{ async_results.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 30
```
The above are just suggestions of what was meant as concurrency for vm start/stop.
